jobs:
  opportunity-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev gcc g++
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas numpy>=1.24.0 scipy>=1.10.0 matplotlib seaborn python-telegram-bot pytz
          
      - name: Check secrets
        run: |
          if [ -z "${{ secrets.TELEGRAM_TOKEN }}" ] || [ -z "${{ secrets.TELEGRAM_CHAT_ID }}" ]; then
            echo "Error: TELEGRAM_TOKEN or TELEGRAM_CHAT_ID is not set in repository secrets"
            exit 1
          else
            echo "Secrets are properly configured"
          fi
          
      - name: Run opportunity scanner
        run: python rsi_bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FORCE_DAILY_SUMMARY: ${{ github.event.inputs.force_summary || 'false' }}
          
      - name: Notify on failure
        if: failure()
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="⚠️ Grid Trading Scanner workflow failed! Check GitHub Actions logs for details." || true
        continue-on-error: true
