name: Grid Trading Scanner

on:
  schedule:
    # Regular scan: Every 2 hours from 1:00 to 17:00 UTC (MYT 9:00–1:00)
    ####- cron: '0 1-17/2 * * *'
    # Urgent scan: Once per hour during off hours (UTC: 17:00–23:59, 0:00; MYT ~1:00–9:00)
    ### - cron: '0 17-23,0 * * *'
  workflow_dispatch:
    inputs:
      force_summary:
        description: 'Force daily summary regardless of opportunities'
        required: false
        default: 'false'
        type: boolean
      scan_frequency:
        description: 'Scan frequency (high/normal/low)'
        required: false
        default: 'normal'
        type: choice
        options:
          - high
          - normal
          - low

jobs:
  grid-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.event.schedule == '0 1-17/2 * * *' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests numpy pandas scipy matplotlib seaborn python-telegram-bot pytz

      - name: Run regular opportunity scan
        run: python rsi_bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FORCE_DAILY_SUMMARY: ${{ github.event.inputs.force_summary || 'false' }}
          SCAN_FREQUENCY: ${{ github.event.inputs.scan_frequency || 'normal' }}

      - name: Notify on failure
        if: failure()
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="⚠️ Grid Trading Scanner failed during regular scan!"
        continue-on-error: true

  urgent-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event.schedule == '0 17-23,0 * * *'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install minimal dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests numpy scipy python-telegram-bot pytz

      - name: Run urgent scan
        run: python rsi_bot.py --urgent-only
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          URGENT_SCAN: 'true'

      - name: Notify on urgent failure
        if: failure()
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="⚠️ Urgent scan failed! Check logs ASAP."
        continue-on-error: true
