
name: Grid Trading Scanner

on:
  schedule:
    # Every 3 hours during Malaysia's day (MYT = UTC+8)
    - cron: '0 0,3,6,9,12,15 * * *'  # UTC → 08:00–23:00 MYT
    # Every hour from 08:00 to 23:00 MYT (urgent scan)
    - cron: '0 0-15 * * *'
  workflow_dispatch:
    inputs:
      force_summary:
        description: 'Force daily summary regardless of opportunities'
        required: false
        default: 'false'
        type: boolean
      scan_frequency:
        description: 'Scan frequency (high/normal/low)'
        required: false
        default: 'normal'
        type: choice
        options:
          - high
          - normal
          - low

jobs:
  grid-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.event.schedule == '0 0,3,6,9,12,15 * * *' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests numpy pandas scipy matplotlib seaborn python-telegram-bot pytz

      - name: Run regular opportunity scan
        run: python rsi_bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FORCE_DAILY_SUMMARY: ${{ github.event.inputs.force_summary || 'false' }}
          SCAN_FREQUENCY: ${{ github.event.inputs.scan_frequency || 'normal' }}

      - name: Notify on failure
        if: failure()
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="⚠️ Grid Trading Scanner failed during regular scan!"
        continue-on-error: true

  urgent-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event.schedule == '0 0-15 * * *'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install minimal dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests numpy scipy python-telegram-bot

      - name: Run urgent scan
        run: python rsi_bot.py --urgent-only
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          URGENT_SCAN: 'true'

      - name: Notify on urgent failure
        if: failure()
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="⚠️ Urgent scan failed! Check logs ASAP."
        continue-on-error: true
